export const STORIES = [
  {
    id: 1,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'ghana.png',
    pathway: 'forest',
    clipUrl: '',
    videoUrl: '',
  },
  {
    id: 2,
    country: 'Tanzania',
    title: 'Carbon project on conservation site',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'ghana.png',
    pathway: 'croplands',
    clipUrl: '',
    videoUrl: '',
  },
  {
    id: 3,
    country: 'Panama',
    title: 'Agroforestry project',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'ghana.png',
    pathway: 'forest',
    clipUrl: '',
    videoUrl: '',
  },
  {
    id: 4,
    country: 'Dominican Republic',
    title: 'Coastal resilience project',
    description: 'Mangroves and coral reefs restoration.',
    image: 'ghana.png',
    pathway: 'wetlands',
    clipUrl: '',
    videoUrl: '',
  },
  {
    id: 5,
    country: 'Tanzania',
    title: 'Carbon project on conservation site',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'ghana.png',
    pathway: 'croplands',
    articleUrl: '',
    clipUrl: '',
  },
  {
    id: 6,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'ghana.png',
    pathway: 'savana',
    articleUrl: '',
    clipUrl: '',
  },
  {
    id: 7,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'ghana.png',
    pathway: 'grasslands',
    clipUrl: '',
    videoUrl: '',
  },
];
