import { Story } from 'types';

export const STORIES: Story[] = [
  {
    id: 1,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'test-1.jpg',
    pathway: 'forest',
    clipUrl: '#',
    videoUrl: '#',
    category: 'Stories from the ground',
  },
  {
    id: 2,
    country: 'Tanzania',
    title: 'Carbon project on conservation site',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'test-2.jpg',
    pathway: 'croplands',
    clipUrl: '#',
    videoUrl: '#',
    category: 'News',
  },
  {
    id: 3,
    country: 'Panama',
    title: 'Agroforestry project',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'test-3.jpg',
    pathway: 'forest',
    clipUrl: '#',
    videoUrl: '#',
    category: 'Stories from the ground',
  },
  {
    id: 4,
    country: 'Dominican Republic',
    title: 'Coastal resilience project',
    description: 'Mangroves and coral reefs restoration.',
    image: 'test-4.jpg',
    pathway: 'wetlands',
    clipUrl: '#',
    videoUrl: '#',
    category: 'Factsheets',
  },
  {
    id: 5,
    country: 'Tanzania',
    title: 'Carbon project on conservation site',
    description:
      'Indigenous-led with key financial schemes to protect biodiversity and benefit local people.',
    image: 'test-1.jpg',
    pathway: 'croplands',
    articleUrl: '#',
    clipUrl: '#',
    category: 'News',
  },
  {
    id: 6,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'test-3.jpg',
    pathway: 'savana',
    articleUrl: '#',
    clipUrl: '#',
    category: 'Stories from the ground',
  },
  {
    id: 7,
    country: 'Ghana',
    title: 'Reforestation project',
    description: 'Local communities are using GIS technology to map forest cover, youth-led.',
    image: 'test-2.jpg',
    pathway: 'grasslands',
    clipUrl: '#',
    videoUrl: '#',
    category: 'Stories from the ground',
  },
];
