name: Deploy with Capistrano

on:
  push:
    branches:
    - main
    - deployment-config

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - uses: miloserdow/capistrano-deploy@v3
      with:
        target: production
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
        enc_rsa_key_pth: ./config/encrypted_keys/deploy_id_ed25519_enc
